name: buf

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
# Omitted
#      - uses: bufbuild/buf-breaking-action@v1
#        with:
#          input: "proto"
          # The 'main' branch of the GitHub repository that defines the module.
          # Note we specify the subdir to compare against.
#          against: "https://github.com/${}.git#branch=main,ref=HEAD~1,subdir=proto"
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "proto"
          buf_token: ${{ secrets.BUF_TOKEN }}