name: buf

on:
  pull_request:
  push:
    branches:
      - main
      - develop

#        on:
#          pull_request:
#          push:
#            branches:
#              - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checking out your repository under $GITHUB_WORKSPACE
      - uses: bufbuild/buf-setup-action@v1
        name: Installing buf CLI to CI/CD pipeline
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
        name: Linting changes in proto files
        with:
          input: "proto"
      - uses: bufbuild/buf-breaking-action@v1
        name: Detect backward compatibility issues
        with:
          input: "proto"
           # The 'main' branch of the GitHub repository that defines the module.
           # Note we specify the subdir to compare against.
          against: "https://github.com/tech-scripter/golang-miniproject-proto.git#branch=main,ref=HEAD~1,subdir=proto"

  push:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
        name: Checking out your repository under $GITHUB_WORKSPACE
      - uses: bufbuild/buf-setup-action@v1
        name: Installing buf CLI to CI/CD pipeline
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-push-action@v1
        name: Pushing changes to BSR
        with:
          input: "proto"
          buf_token: ${{ secrets.BUF_TOKEN }}